platform :ios, '6.1' 
pod 'SDWebImage', '~> 3.7'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SSKeychain'
pod 'FMDB'
platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"
pod 'Masonry'
platform :ios, '7.0'
pod 'KINWebBrowser'
